"""
mylist_routes.py

Shopping list endpoints that extend the core MyList functionality:

  POST /api/kitchen/generate_autogenerated_list  — build/refresh the
       autogenerated shopping list from low-stock inventory items and
       missing meal-plan ingredients for a given date.

  POST /api/kitchen/edit_mylist_item             — edit any field of an
       item across all bucket types (mylist, requested, autogenerated_list)
       with bucket-specific permission checks.
"""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required, get_jwt
from datetime import datetime, timezone
import uuid

from db_connection import get_session
from models import Kitchen, KitchenMember, KitchenItem, MyList, MealPlan

mylist_blueprint = Blueprint('mylist_blueprint', __name__)


# ── Endpoints ────────────────────────────────────────────────────────────────

@mylist_blueprint.route('/api/kitchen/generate_autogenerated_list', methods=['POST'])
@jwt_required()
def generate_autogenerated_list():
    """
    Generate (or refresh) the autogenerated shopping list for a kitchen.

    The list is built from two sources:
      1. Low-stock items currently in the kitchen inventory.
      2. Missing ingredients from meal plans scheduled on the given date.

    Any previously generated autogenerated_list items for this kitchen are
    deleted first, so calling this endpoint is always idempotent — it always
    produces a fresh, up-to-date list.

    Only host or co-host can trigger generation.

    Request body:
        kitchen_id  (int|str)  – required
        date        (str)      – required, format YYYY-MM-DD
                                 Used to look up meal plans for that day.
    """
    session = get_session()
    try:
        user_identity = get_jwt()
        user_id = int(user_identity['user_id'])
        data = request.get_json()

        kitchen_id = data.get('kitchen_id')
        date_str = data.get('date', '').strip()

        # ── Validate inputs ────────────────────────────────────────────────
        try:
            kitchen_id = int(kitchen_id)
        except (ValueError, TypeError):
            return jsonify({'error': 'Invalid kitchen ID'}), 400

        if not date_str:
            return jsonify({'error': 'date is required (format: YYYY-MM-DD)'}), 400

        try:
            datetime.strptime(date_str, '%Y-%m-%d')
        except ValueError:
            return jsonify({'error': 'Invalid date format. Use YYYY-MM-DD'}), 400

        # ── Kitchen & membership check ──────────────────────────────────────
        kitchen = session.query(Kitchen).filter(Kitchen.id == kitchen_id).first()
        if not kitchen:
            return jsonify({'error': 'Kitchen not found'}), 404

        is_host = kitchen.host_id == user_id
        is_co_host = session.query(KitchenMember).filter(
            KitchenMember.kitchen_id == kitchen_id,
            KitchenMember.user_id == user_id,
            KitchenMember.member_type == 'co-host'
        ).first() is not None

        if not (is_host or is_co_host):
            return jsonify({'error': 'Only host or co-host can generate the autogenerated list'}), 403

        # ── Helper: stock-status identical to get_all_mylist_items ─────────
        def is_low_stock(quantity, unit):
            """Return True when an inventory item is considered low-stock."""
            try:
                qty = float(quantity)
                unit_lower = (unit or '').lower()
                if qty == 0:
                    return True   # out_of_stock is a subset of low
                if unit_lower in ['count', 'piece', 'pieces']:
                    return qty <= 2
                elif unit_lower in ['kg', 'litre', 'liter', 'l']:
                    return qty <= 0.5
                elif unit_lower in ['grams', 'g', 'ml', 'millilitre']:
                    return qty <= 100
                else:
                    return qty <= 1
            except Exception:
                return False

        # ── SOURCE 1: Low-stock inventory items ────────────────────────────
        inventory_items = session.query(KitchenItem).filter(
            KitchenItem.kitchen_id == kitchen_id
        ).all()

        low_stock_items = [
            item for item in inventory_items
            if is_low_stock(item.quantity, item.unit)
        ]

        # ── SOURCE 2: Missing meal-plan ingredients for the given date ──────
        meal_plans_on_date = session.query(MealPlan).filter(
            MealPlan.kitchen_id == kitchen_id,
            MealPlan.date == date_str
        ).all()

        # Collect unique missing ingredients across all meal plans for the date.
        # missing_items_list entries have the shape: {name, amount, unit}
        # De-duplicated by normalised ingredient name.
        missing_ingredients = {}   # normalised_name -> {name, quantity, unit}
        for plan in meal_plans_on_date:
            raw_missing = plan.missing_items_list or []
            for ingredient in raw_missing:
                ing_name = (ingredient.get('name') or '').strip()
                if not ing_name:
                    continue
                norm_key = ing_name.lower()
                if norm_key not in missing_ingredients:
                    try:
                        qty = float(ingredient.get('amount') or 1)
                    except (ValueError, TypeError):
                        qty = 1.0
                    ing_unit = (ingredient.get('unit') or 'count').strip() or 'count'
                    missing_ingredients[norm_key] = {
                        'name': ing_name,
                        'quantity': qty,
                        'unit': ing_unit
                    }

        # ── Delete existing autogenerated_list items for this kitchen ───────
        session.query(MyList).filter(
            MyList.kitchen_id == kitchen_id,
            MyList.bucket_type == 'autogenerated_list'
        ).delete(synchronize_session=False)

        # ── Build the new list ──────────────────────────────────────────────
        now = datetime.now(timezone.utc)
        added_items = []

        # Track normalised names to avoid duplicates between the two sources
        added_names = set()

        # Add low-stock items
        for inv_item in low_stock_items:
            norm_key = inv_item.name.strip().lower()
            if norm_key in added_names:
                continue
            added_names.add(norm_key)

            new_item = MyList(
                item_id=uuid.uuid4().hex,
                kitchen_id=kitchen_id,
                user_id=user_id,
                name=inv_item.name.strip(),
                quantity=inv_item.quantity,
                unit=inv_item.unit,
                bucket_type='autogenerated_list',
                thumbnail=inv_item.thumbnail,
                expiry_date=inv_item.expiry_date,
                auto_added=True,
                created_at=now,
                modified_at=None
            )
            session.add(new_item)
            added_items.append({
                'item_id': new_item.item_id,
                'name': new_item.name,
                'quantity': new_item.quantity,
                'unit': new_item.unit,
                'source': 'low_stock'
            })

        # Add missing meal-plan ingredients (skip if already covered by low stock)
        for norm_key, ing in missing_ingredients.items():
            if norm_key in added_names:
                continue
            added_names.add(norm_key)

            new_item = MyList(
                item_id=uuid.uuid4().hex,
                kitchen_id=kitchen_id,
                user_id=user_id,
                name=ing['name'],
                quantity=ing['quantity'],
                unit=ing['unit'],
                bucket_type='autogenerated_list',
                thumbnail=None,
                expiry_date=None,
                auto_added=True,
                created_at=now,
                modified_at=None
            )
            session.add(new_item)
            added_items.append({
                'item_id': new_item.item_id,
                'name': new_item.name,
                'quantity': new_item.quantity,
                'unit': new_item.unit,
                'source': 'missing_ingredient'
            })

        session.commit()

        return jsonify({
            'message': f'Autogenerated list created with {len(added_items)} item(s).',
            'total_items': len(added_items),
            'low_stock_count': sum(1 for i in added_items if i['source'] == 'low_stock'),
            'missing_ingredients_count': sum(1 for i in added_items if i['source'] == 'missing_ingredient'),
            'items': added_items
        }), 201

    except Exception as e:
        session.rollback()
        return jsonify({'error': str(e)}), 500
    finally:
        session.close()


@mylist_blueprint.route('/api/kitchen/edit_mylist_item', methods=['POST'])
@jwt_required()
def edit_mylist_item():
    """
    Edit an item that exists in any bucket of the shopping list
    (mylist, requested, or autogenerated_list).

    Permission rules:
      - autogenerated_list items  → only host or co-host
      - mylist items              → only host or co-host
      - requested items           → only the user who originally requested it

    At least one editable field must be provided:
        name, quantity, unit, thumbnail, expiry_date

    Request body:
        kitchen_id   (int|str)  – required
        item_id      (str)      – required, the UUID hex of the item
        name         (str)      – optional
        quantity     (number)   – optional
        unit         (str)      – optional
        thumbnail    (str)      – optional (base64 image or null to clear)
        expiry_date  (str)      – optional (e.g. "7 days" or null to clear)
    """
    session = get_session()
    try:
        user_identity = get_jwt()
        user_id = int(user_identity['user_id'])
        data = request.get_json()

        kitchen_id = data.get('kitchen_id')
        item_id = (data.get('item_id') or '').strip()

        # ── Validate IDs ────────────────────────────────────────────────────
        try:
            kitchen_id = int(kitchen_id)
        except (ValueError, TypeError):
            return jsonify({'error': 'Invalid kitchen ID'}), 400

        if not item_id:
            return jsonify({'error': 'item_id is required'}), 400

        # ── Kitchen check ───────────────────────────────────────────────────
        kitchen = session.query(Kitchen).filter(Kitchen.id == kitchen_id).first()
        if not kitchen:
            return jsonify({'error': 'Kitchen not found'}), 404

        # ── Fetch item ──────────────────────────────────────────────────────
        item = session.query(MyList).filter(
            MyList.kitchen_id == kitchen_id,
            MyList.item_id == item_id
        ).first()

        if not item:
            return jsonify({'error': 'Item not found'}), 404

        # ── Permission check based on bucket_type ───────────────────────────
        is_host = kitchen.host_id == user_id
        is_co_host = session.query(KitchenMember).filter(
            KitchenMember.kitchen_id == kitchen_id,
            KitchenMember.user_id == user_id,
            KitchenMember.member_type == 'co-host'
        ).first() is not None

        if item.bucket_type in ('mylist', 'autogenerated_list'):
            if not (is_host or is_co_host):
                return jsonify({
                    'error': f'Only host or co-host can edit {item.bucket_type} items'
                }), 403
        elif item.bucket_type == 'requested':
            if item.user_id != user_id:
                return jsonify({'error': 'You can only edit your own requested items'}), 403
        else:
            # Unknown bucket type — restrict to host/co-host as a safe default
            if not (is_host or is_co_host):
                return jsonify({'error': 'Insufficient permissions to edit this item'}), 403

        # ── Validate that at least one field is being changed ───────────────
        editable_fields = ['name', 'quantity', 'unit', 'thumbnail', 'expiry_date']
        provided = [f for f in editable_fields if f in data]
        if not provided:
            return jsonify({
                'error': 'At least one field must be provided: name, quantity, unit, thumbnail, expiry_date'
            }), 400

        # ── Apply updates ───────────────────────────────────────────────────
        if 'name' in data:
            name_val = (data['name'] or '').strip()
            if not name_val:
                return jsonify({'error': 'name cannot be empty'}), 400
            item.name = name_val

        if 'quantity' in data:
            try:
                qty = float(data['quantity'])
                if qty < 0:
                    return jsonify({'error': 'quantity must be a non-negative number'}), 400
                item.quantity = qty
            except (ValueError, TypeError):
                return jsonify({'error': 'quantity must be a valid number'}), 400

        if 'unit' in data:
            unit_val = (data['unit'] or '').strip()
            if not unit_val:
                return jsonify({'error': 'unit cannot be empty'}), 400
            item.unit = unit_val

        # thumbnail and expiry_date accept None to clear the field
        if 'thumbnail' in data:
            item.thumbnail = data['thumbnail']

        if 'expiry_date' in data:
            item.expiry_date = data['expiry_date']

        item.modified_at = datetime.now(timezone.utc)
        session.commit()

        return jsonify({
            'message': 'Item updated successfully',
            'item_id': item.item_id,
            'bucket_type': item.bucket_type,
            'updated_fields': provided
        }), 200

    except Exception as e:
        session.rollback()
        return jsonify({'error': str(e)}), 500
    finally:
        session.close()